eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
            allowedHeaders:   # ⚠️ voir erreur 2
              - Content-Type

      discovery:
        locator:
          enabled: true

      routes:
        - id: users-service
          uri: http://localhost:8087
          predicates:
            - Path=/users/**,/auth/**
            - Method=GET,POST,PUT,DELETE,OPTIONS

server:
  port: 8085

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

#eureka:
#  client:
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#
#  cloud:
#    gateway:
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "http://localhost:4200"
#            allowedMethods:
#              - PUT
#              - GET
#              - POST
#              - DELETE
#            AllowedHeaders:
#              - Content-Type
#      discovery:
#        locator:
#          enabled: true
#
#      routes:
#        - id: users-service
#          uri: http://localhost:8087
#          predicates:
#            - Path=/users/**
#            - Method=GET,POST,PUT,DELETE,OPTIONS
#
#
#  logging:
#    level:
#      org.springframework.cloud.gateway: DEBUG
#
#  application:
#    name : gateway-service
#
#server:
#  port: 8085
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#
#
