
server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native

    
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
#            file:///C:/workSpaceSpring/MS/backOffice/config-service/src/main/resources/configurations

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
